import mongoose from "mongoose";
import dotenv from "dotenv";
import Food from "./models/foodModel.js";             


dotenv.config();

export const foods = [
  {
    name: "Boiled Eggs (2)",
    brand: "Generic",
    category: "Natural",
    price: 16,
    protein: 12,
    calories: 140,
    carbs: 1,
    fat: 10,
    fiber: 0,
    servingSize: "2 eggs (100g)",
    image: "images/boiledeggs.jpg",
  },
  {
    name: "Paneer (100g)",
    brand: "Amul",
    category: "Dairy",
    price: 80,
    protein: 18,
    calories: 260,
    carbs: 4,
    fat: 21,
    fiber: 0,
    servingSize: "100g",
    image: "images/amulpaneer.png",
  },
  {
    name: "Grilled Chicken Breast (100g)",
    brand: "Generic",
    category: "Meat",
    price: 120,
    protein: 31,
    calories: 165,
    carbs: 0,
    fat: 3.5,
    fiber: 0,
    servingSize: "100g",
    image: "images/grilledchicken.jpg",
  },
  {
    name: "Greek Yogurt (200g)",
    brand: "Epigamia",
    category: "Dairy",
    price: 60,
    protein: 10,
    calories: 130,
    carbs: 12,
    fat: 3,
    fiber: 0,
    servingSize: "200g cup",
    image: "images/epigamia.png",
  },
  {
    name: "Protein Bar (Chocolate)",
    brand: "RiteBite",
    category: "Packaged",
    price: 80,
    protein: 20,
    calories: 220,
    carbs: 24,
    fat: 8,
    fiber: 5,
    servingSize: "60g bar",
    image: "images/maxprotein",
  },
  {
    name: "Whey Protein (1 scoop)",
    brand: "Optimum Nutrition",
    category: "Supplement",
    price: 90,
    protein: 24,
    calories: 120,
    carbs: 3,
    fat: 1,
    fiber: 0,
    servingSize: "30g scoop",
    image: "images/on.png",
  },
  {
    name: "Tofu (100g)",
    brand: "Vezlay",
    category: "Plant-Based",
    price: 60,
    protein: 8,
    calories: 95,
    carbs: 2,
    fat: 5,
    fiber: 1,
    servingSize: "100g",
    image: "images/tofu.png",
  },
  {
    name: "Lentils (Cooked 1 cup)",
    brand: "Generic",
    category: "Legume",
    price: 25,
    protein: 18,
    calories: 230,
    carbs: 40,
    fat: 1,
    fiber: 15,
    servingSize: "200g (1 cup)",
    image: "images/lentils.png",
  },
  {
    name: "Peanut Butter (2 tbsp)",
    brand: "Pintola",
    category: "Nut Butter",
    price: 25,
    protein: 8,
    calories: 190,
    carbs: 6,
    fat: 16,
    fiber: 2,
    servingSize: "32g (2 tbsp)",
    image: "images/pb.png",
  },
  {
    name: "Sprouts (100g)",
    brand: "Generic",
    category: "Plant-Based",
    price: 20,
    protein: 7,
    calories: 100,
    carbs: 17,
    fat: 1,
    fiber: 2,
    servingSize: "100g",
    image: "images/sprouts.png",
  },
  {
    name: "Fish (100g)",
    brand: "Freshwater",
    category: "Seafood",
    price: 130,
    protein: 22,
    calories: 180,
    carbs: 0,
    fat: 10,
    fiber: 0,
    servingSize: "100g",
    image: "images/fish.png",
  },
  {
    name: "Protein Shake (Chocolate)",
    brand: "MuscleBlaze",
    category: "Supplement",
    price: 120,
    protein: 18,
    calories: 200,
    carbs: 6,
    fat: 3,
    fiber: 1,
    servingSize: "330ml bottle",
    image: "image/mbps.png",
  },
  {
    name: "Soya Chunks (100g)",
    brand: "Nutrela",
    category: "Plant-Based",
    price: 35,
    protein: 52,
    calories: 345,
    carbs: 33,
    fat: 0.5,
    fiber: 13,
    servingSize: "100g dry",
    image: "images/soyachunks.png",
  },
  {
    name: "Oats (100g)",
    brand: "Quaker",
    category: "Grain",
    price: 40,
    protein: 13,
    calories: 380,
    carbs: 67,
    fat: 7,
    fiber: 10,
    servingSize: "100g",
    image: "images/oats.png",
  },
  {
    name: "Milk (200ml)",
    brand: "Amul",
    category: "Dairy",
    price: 20,
    protein: 6,
    calories: 130,
    carbs: 10,
    fat: 7,
    fiber: 0,
    servingSize: "200ml",
    image: "images/milk.png",
  },
  {
    name: "Protein Cookies",
    brand: "The Whole Truth",
    category: "Packaged",
    price: 70,
    protein: 20,
    calories: 220,
    carbs: 20,
    fat: 9,
    fiber: 3,
    servingSize: "50g pack",
    image: "wt.png",
  },
  
  {
    name: "Cottage Cheese Sandwich",
    brand: "Generic",
    category: "Meal",
    price: 90,
    protein: 16,
    calories: 300,
    carbs: 30,
    fat: 10,
    fiber: 4,
    servingSize: "1 sandwich (200g)",
    image: "sw.png",
  },
  {
    name: "Mixed Nuts (50g)",
    brand: "Happilo",
    category: "Snack",
    price: 60,
    protein: 8,
    calories: 280,
    carbs: 10,
    fat: 24,
    fiber: 3,
    servingSize: "50g",
    image: "nuts.png",
  },
  {
    name: "Egg White Omelette",
    brand: "Generic",
    category: "Natural",
    price: 50,
    protein: 14,
    calories: 110,
    carbs: 2,
    fat: 4,
    fiber: 0,
    servingSize: "2 egg whites (120g)",
    image: "eggwhite.png",
  },
    {
    name: "Salmon Fillet (200g)",
    brand: "FreshCatch",
    category: "Seafood",
    price: 450,
    protein: 46,
    calories: 400,
    carbs: 0,
    fat: 28,
    fiber: 0,
    servingSize: "200g fillet",
    image: "salmon.png",
  },
  {
    name: "Tuna Steak (200g)",
    brand: "Ocean's Pride",
    category: "Seafood",
    price: 380,
    protein: 50,
    calories: 360,
    carbs: 0,
    fat: 20,
    fiber: 0,
    servingSize: "200g steak",
    image: "tuna.png",
  },
  {
    name: "Lobster (250g)",
    brand: "Coastal Fresh",
    category: "Seafood",
    price: 850,
    protein: 55,
    calories: 420,
    carbs: 2,
    fat: 18,
    fiber: 0,
    servingSize: "250g",
    image: "lobster.jpg",
  },
  {
    name: "Steak (200g)",
    brand: "TenderCuts",
    category: "Meat",
    price: 600,
    protein: 48,
    calories: 500,
    carbs: 0,
    fat: 32,
    fiber: 0,
    servingSize: "200g steak",
    image: "steak.png",
  },
  {
    name: "Whey Isolate (1 scoop)",
    brand: "MyProtein",
    category: "Supplement",
    price: 120,
    protein: 27,
    calories: 115,
    carbs: 1,
    fat: 1,
    fiber: 0,
    servingSize: "30g scoop",
    image: "wheyisolate.png",
  },
  {
    name: "Shrimp (200g)",
    brand: "FreshBay",
    category: "Seafood",
    price: 300,
    protein: 42,
    calories: 280,
    carbs: 0,
    fat: 8,
    fiber: 0,
    servingSize: "200g",
    image: "shrimp.png",
  },
  {
    name: "Beef Jerky (100g)",
    brand: "Jack Link’s",
    category: "Snack",
    price: 250,
    protein: 33,
    calories: 300,
    carbs: 5,
    fat: 20,
    fiber: 0,
    servingSize: "100g pack",
    image: "images/beefjerky.png",
  },
  {
    name: "Grilled Lamb Chops (250g)",
    brand: "Gourmet Grill",
    category: "Meat",
    price: 900,
    protein: 60,
    calories: 600,
    carbs: 0,
    fat: 40,
    fiber: 0,
    servingSize: "250g",
    image: "images/lambchops.png",
  },
  {
    name: "Prawns (200g)",
    brand: "Seabreeze",
    category: "Seafood",
    price: 350,
    protein: 40,
    calories: 260,
    carbs: 1,
    fat: 6,
    fiber: 0,
    servingSize: "200g",
    image: "images/prawns.png",
  },
  
  {
    name: "Turkey Breast (150g)",
    brand: "DeliFresh",
    category: "Meat",
    price: 420,
    protein: 40,
    calories: 230,
    carbs: 0,
    fat: 5,
    fiber: 0,
    servingSize: "150g",
    image: "images/turkeybreast.png",
  },
  {
    name: "Crab Meat (200g)",
    brand: "Ocean Fresh",
    category: "Seafood",
    price: 550,
    protein: 44,
    calories: 320,
    carbs: 0,
    fat: 15,
    fiber: 0,
    servingSize: "200g",
    image: "images/crab.png",
  },
  {
    name: "Chicken Sausage (150g)",
    brand: "Venky’s",
    category: "Meat",
    price: 150,
    protein: 28,
    calories: 280,
    carbs: 2,
    fat: 20,
    fiber: 0,
    servingSize: "150g",
    image: "images/sausage.png",
  },
  {
    name: "Egg Protein Powder (1 scoop)",
    brand: "NOW Sports",
    category: "Supplement",
    price: 150,
    protein: 24,
    calories: 120,
    carbs: 1,
    fat: 2,
    fiber: 0,
    servingSize: "30g scoop",
    image: "images/eggprotein.png",
  },
  {
  name: "Rajma (Cooked 1 cup)",
  brand: "Generic",
  category: "Legume",
  price: 30,
  protein: 15,
  calories: 220,
  carbs: 38,
  fat: 1,
  fiber: 12,
  servingSize: "200g (1 cup)",
  image: "images/rajma.png",
},
{
  name: "Black Chana (Cooked 1 cup)",
  brand: "Generic",
  category: "Legume",
  price: 28,
  protein: 14,
  calories: 210,
  carbs: 35,
  fat: 2,
  fiber: 10,
  servingSize: "200g (1 cup)",
  image: "images/blackchana.png",
},
{
  name: "Chickpeas (Cooked 1 cup)",
  brand: "Generic",
  category: "Legume",
  price: 25,
  protein: 14,
  calories: 240,
  carbs: 45,
  fat: 4,
  fiber: 12,
  servingSize: "200g (1 cup)",
  image: "images/chickpeas.png",
},
{
  name: "Almonds (50g)",
  brand: "Happilo",
  category: "Snack",
  price: 75,
  protein: 10,
  calories: 290,
  carbs: 8,
  fat: 25,
  fiber: 6,
  servingSize: "50g",
  image: "images/almonds.png",
},
{
  name: "Walnuts (50g)",
  brand: "Happilo",
  category: "Snack",
  price: 90,
  protein: 7,
  calories: 320,
  carbs: 7,
  fat: 30,
  fiber: 3,
  servingSize: "50g",
  image: "images/walnuts.png",
},
{
  name: "Brown Rice (1 cup cooked)",
  brand: "Generic",
  category: "Grain",
  price: 25,
  protein: 5,
  calories: 215,
  carbs: 45,
  fat: 2,
  fiber: 4,
  servingSize: "200g (1 cup)",
  image: "images/brownrice.png",
},
{
  name: "Curd (200g)",
  brand: "Amul",
  category: "Dairy",
  price: 25,
  protein: 7,
  calories: 140,
  carbs: 8,
  fat: 7,
  fiber: 0,
  servingSize: "200g",
  image: "images/curd.png",
},
{
  name: "Soy Milk (200ml)",
  brand: "Sofit",
  category: "Dairy Alternative",
  price: 35,
  protein: 6,
  calories: 120,
  carbs: 14,
  fat: 4,
  fiber: 1,
  servingSize: "200ml",
  image: "images/soymilk.png",
},
{
  name: "Chia Seeds (2 tbsp)",
  brand: "True Elements",
  category: "Plant-Based",
  price: 20,
  protein: 4,
  calories: 138,
  carbs: 12,
  fat: 9,
  fiber: 10,
  servingSize: "2 tbsp (28g)",
  image: "images/chiaseeds.png",
},
{
  name: "Pumpkin Seeds (30g)",
  brand: "Happilo",
  category: "Snack",
  price: 30,
  protein: 9,
  calories: 160,
  carbs: 4,
  fat: 14,
  fiber: 2,
  servingSize: "30g",
  image: "images/pumpkinseeds.png",
},

{
  name: "Moong Dal Cheela (2 pieces)",
  brand: "Homemade",
  category: "Meal",
  price: 40,
  protein: 14,
  calories: 200,
  carbs: 20,
  fat: 6,
  fiber: 5,
  servingSize: "2 cheelas (150g)",
  image: "images/moongcheela.png",
},
{
  name: "Quinoa (1 cup cooked)",
  brand: "Organic India",
  category: "Grain",
  price: 50,
  protein: 8,
  calories: 220,
  carbs: 39,
  fat: 3,
  fiber: 5,
  servingSize: "200g (1 cup)",
  image: "images/quinoa.png",
},
{
  name: "Brown Bread Peanut Butter Sandwich",
  brand: "Homemade",
  category: "Snack",
  price: 35,
  protein: 10,
  calories: 280,
  carbs: 28,
  fat: 14,
  fiber: 4,
  servingSize: "1 sandwich (120g)",
  image: "images/pbsandwich.png",
},
{
  name: "Hummus (100g)",
  brand: "Wingreens",
  category: "Plant-Based",
  price: 50,
  protein: 8,
  calories: 210,
  carbs: 14,
  fat: 12,
  fiber: 4,
  servingSize: "100g",
  image: "images/hummus.png",
},


];


async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    await Food.deleteMany({});
    await Food.insertMany(foods);
    console.log("✅ Data seeded");
    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

seed();