import mongoose from "mongoose";
import dotenv from "dotenv";
import Food from "./models/foodModel.js";             


dotenv.config();

export const foods = [
  {
    name: "Boiled Eggs (2)",
    brand: "Generic",
    category: "Natural",
    price: 16,
    protein: 12,
    calories: 140,
    carbs: 1,
    fat: 10,
    fiber: 0,
    servingSize: "2 eggs (100g)",
    image: "https://i.imgur.com/3C4zC4y.jpg",
  },
  {
    name: "Paneer (100g)",
    brand: "Amul",
    category: "Dairy",
    price: 80,
    protein: 18,
    calories: 260,
    carbs: 4,
    fat: 21,
    fiber: 0,
    servingSize: "100g",
    image: "https://i.imgur.com/EWwTgvl.jpg",
  },
  {
    name: "Grilled Chicken Breast (100g)",
    brand: "Generic",
    category: "Meat",
    price: 120,
    protein: 31,
    calories: 165,
    carbs: 0,
    fat: 3.5,
    fiber: 0,
    servingSize: "100g",
    image: "https://i.imgur.com/WmKkLMh.jpg",
  },
  {
    name: "Greek Yogurt (200g)",
    brand: "Epigamia",
    category: "Dairy",
    price: 60,
    protein: 10,
    calories: 130,
    carbs: 12,
    fat: 3,
    fiber: 0,
    servingSize: "200g cup",
    image: "https://i.imgur.com/0ZlR3f3.jpg",
  },
  {
    name: "Protein Bar (Chocolate)",
    brand: "RiteBite",
    category: "Packaged",
    price: 80,
    protein: 20,
    calories: 220,
    carbs: 24,
    fat: 8,
    fiber: 5,
    servingSize: "60g bar",
    image: "https://i.imgur.com/MqA6Juq.jpg",
  },
  {
    name: "Whey Protein (1 scoop)",
    brand: "Optimum Nutrition",
    category: "Supplement",
    price: 90,
    protein: 24,
    calories: 120,
    carbs: 3,
    fat: 1,
    fiber: 0,
    servingSize: "30g scoop",
    image: "https://i.imgur.com/Hh8s8Rn.jpg",
  },
  {
    name: "Tofu (100g)",
    brand: "Vezlay",
    category: "Plant-Based",
    price: 60,
    protein: 8,
    calories: 95,
    carbs: 2,
    fat: 5,
    fiber: 1,
    servingSize: "100g",
    image: "https://i.imgur.com/BJzTdGK.jpg",
  },
  {
    name: "Lentils (Cooked 1 cup)",
    brand: "Generic",
    category: "Legume",
    price: 25,
    protein: 18,
    calories: 230,
    carbs: 40,
    fat: 1,
    fiber: 15,
    servingSize: "200g (1 cup)",
    image: "https://i.imgur.com/FV5eHFG.jpg",
  },
  {
    name: "Peanut Butter (2 tbsp)",
    brand: "Pintola",
    category: "Nut Butter",
    price: 25,
    protein: 8,
    calories: 190,
    carbs: 6,
    fat: 16,
    fiber: 2,
    servingSize: "32g (2 tbsp)",
    image: "https://i.imgur.com/7QwJ7jP.jpg",
  },
  {
    name: "Sprouts (100g)",
    brand: "Generic",
    category: "Plant-Based",
    price: 20,
    protein: 7,
    calories: 100,
    carbs: 17,
    fat: 1,
    fiber: 2,
    servingSize: "100g",
    image: "https://i.imgur.com/TsX5QvO.jpg",
  },
  {
    name: "Fish (100g)",
    brand: "Freshwater",
    category: "Seafood",
    price: 130,
    protein: 22,
    calories: 180,
    carbs: 0,
    fat: 10,
    fiber: 0,
    servingSize: "100g",
    image: "https://i.imgur.com/bbnoo6J.jpg",
  },
  {
    name: "Protein Shake (Chocolate)",
    brand: "MuscleBlaze",
    category: "Supplement",
    price: 120,
    protein: 25,
    calories: 200,
    carbs: 6,
    fat: 3,
    fiber: 1,
    servingSize: "330ml bottle",
    image: "https://i.imgur.com/qZIvx6U.jpg",
  },
  {
    name: "Soya Chunks (100g)",
    brand: "Nutrela",
    category: "Plant-Based",
    price: 35,
    protein: 52,
    calories: 345,
    carbs: 33,
    fat: 0.5,
    fiber: 13,
    servingSize: "100g dry",
    image: "https://i.imgur.com/vCjj3yo.jpg",
  },
  {
    name: "Oats (100g)",
    brand: "Quaker",
    category: "Grain",
    price: 40,
    protein: 13,
    calories: 380,
    carbs: 67,
    fat: 7,
    fiber: 10,
    servingSize: "100g",
    image: "https://i.imgur.com/Qs1kxQp.jpg",
  },
  {
    name: "Milk (200ml)",
    brand: "Amul",
    category: "Dairy",
    price: 20,
    protein: 6,
    calories: 130,
    carbs: 10,
    fat: 7,
    fiber: 0,
    servingSize: "200ml",
    image: "https://i.imgur.com/hzFJrKf.jpg",
  },
  {
    name: "Protein Cookies",
    brand: "The Whole Truth",
    category: "Packaged",
    price: 70,
    protein: 12,
    calories: 220,
    carbs: 20,
    fat: 9,
    fiber: 3,
    servingSize: "50g pack",
    image: "https://i.imgur.com/LGmAdpv.jpg",
  },
  {
    name: "Protein Shake (Strawberry)",
    brand: "MyFitness",
    category: "Supplement",
    price: 110,
    protein: 23,
    calories: 190,
    carbs: 5,
    fat: 2,
    fiber: 0,
    servingSize: "330ml bottle",
    image: "https://i.imgur.com/AGfrupA.jpg",
  },
  {
    name: "Cottage Cheese Sandwich",
    brand: "Generic",
    category: "Meal",
    price: 90,
    protein: 16,
    calories: 300,
    carbs: 30,
    fat: 10,
    fiber: 4,
    servingSize: "1 sandwich (200g)",
    image: "https://i.imgur.com/qBtVXZh.jpg",
  },
  {
    name: "Mixed Nuts (50g)",
    brand: "Happilo",
    category: "Snack",
    price: 60,
    protein: 8,
    calories: 280,
    carbs: 10,
    fat: 24,
    fiber: 3,
    servingSize: "50g",
    image: "https://i.imgur.com/ay8C6pB.jpg",
  },
  {
    name: "Egg White Omelette",
    brand: "Generic",
    category: "Natural",
    price: 50,
    protein: 14,
    calories: 110,
    carbs: 2,
    fat: 4,
    fiber: 0,
    servingSize: "2 egg whites (120g)",
    image: "https://i.imgur.com/dmgoUUt.jpg",
  },
    {
    name: "Salmon Fillet (200g)",
    brand: "FreshCatch",
    category: "Seafood",
    price: 450,
    protein: 46,
    calories: 400,
    carbs: 0,
    fat: 28,
    fiber: 0,
    servingSize: "200g fillet",
    image: "https://i.imgur.com/5WqkqIw.jpg",
  },
  {
    name: "Tuna Steak (200g)",
    brand: "Ocean's Pride",
    category: "Seafood",
    price: 380,
    protein: 50,
    calories: 360,
    carbs: 0,
    fat: 20,
    fiber: 0,
    servingSize: "200g steak",
    image: "https://i.imgur.com/6mQnS7F.jpg",
  },
  {
    name: "Lobster (250g)",
    brand: "Coastal Fresh",
    category: "Seafood",
    price: 850,
    protein: 55,
    calories: 420,
    carbs: 2,
    fat: 18,
    fiber: 0,
    servingSize: "250g",
    image: "https://i.imgur.com/XByhfgk.jpg",
  },
  {
    name: "Steak (200g)",
    brand: "TenderCuts",
    category: "Meat",
    price: 600,
    protein: 48,
    calories: 500,
    carbs: 0,
    fat: 32,
    fiber: 0,
    servingSize: "200g steak",
    image: "https://i.imgur.com/8Kptd6O.jpg",
  },
  {
    name: "Whey Isolate (1 scoop)",
    brand: "MyProtein",
    category: "Supplement",
    price: 120,
    protein: 27,
    calories: 115,
    carbs: 1,
    fat: 1,
    fiber: 0,
    servingSize: "30g scoop",
    image: "https://i.imgur.com/9Gn3K8E.jpg",
  },
  {
    name: "Shrimp (200g)",
    brand: "FreshBay",
    category: "Seafood",
    price: 300,
    protein: 42,
    calories: 280,
    carbs: 0,
    fat: 8,
    fiber: 0,
    servingSize: "200g",
    image: "https://i.imgur.com/gB3b6o3.jpg",
  },
  {
    name: "Beef Jerky (100g)",
    brand: "Jack Link’s",
    category: "Snack",
    price: 250,
    protein: 33,
    calories: 300,
    carbs: 5,
    fat: 20,
    fiber: 0,
    servingSize: "100g pack",
    image: "https://i.imgur.com/xZrj6Vt.jpg",
  },
  {
    name: "Grilled Lamb Chops (250g)",
    brand: "Gourmet Grill",
    category: "Meat",
    price: 900,
    protein: 60,
    calories: 600,
    carbs: 0,
    fat: 40,
    fiber: 0,
    servingSize: "250g",
    image: "https://i.imgur.com/EZYp4Rt.jpg",
  },
  {
    name: "Prawns (200g)",
    brand: "Seabreeze",
    category: "Seafood",
    price: 350,
    protein: 40,
    calories: 260,
    carbs: 1,
    fat: 6,
    fiber: 0,
    servingSize: "200g",
    image: "https://i.imgur.com/fNng3Nb.jpg",
  },
  {
    name: "Protein Smoothie (500ml)",
    brand: "MuscleBlaze",
    category: "Supplement",
    price: 250,
    protein: 45,
    calories: 350,
    carbs: 12,
    fat: 4,
    fiber: 1,
    servingSize: "500ml bottle",
    image: "https://i.imgur.com/AJjI7XK.jpg",
  },
  {
    name: "Turkey Breast (150g)",
    brand: "DeliFresh",
    category: "Meat",
    price: 420,
    protein: 40,
    calories: 230,
    carbs: 0,
    fat: 5,
    fiber: 0,
    servingSize: "150g",
    image: "https://i.imgur.com/rYyKQ4s.jpg",
  },
  {
    name: "Crab Meat (200g)",
    brand: "Ocean Fresh",
    category: "Seafood",
    price: 550,
    protein: 44,
    calories: 320,
    carbs: 0,
    fat: 15,
    fiber: 0,
    servingSize: "200g",
    image: "https://i.imgur.com/pTkjBkD.jpg",
  },
  {
    name: "Mutton Curry (200g)",
    brand: "HomeMade",
    category: "Meal",
    price: 280,
    protein: 35,
    calories: 420,
    carbs: 8,
    fat: 25,
    fiber: 0,
    servingSize: "200g",
    image: "https://i.imgur.com/2yAlTje.jpg",
  },
  {
    name: "Chicken Sausage (150g)",
    brand: "Venky’s",
    category: "Meat",
    price: 150,
    protein: 28,
    calories: 280,
    carbs: 2,
    fat: 20,
    fiber: 0,
    servingSize: "150g",
    image: "https://i.imgur.com/8o3d7He.jpg",
  },
  {
    name: "Egg Protein Powder (1 scoop)",
    brand: "NOW Sports",
    category: "Supplement",
    price: 150,
    protein: 24,
    calories: 120,
    carbs: 1,
    fat: 2,
    fiber: 0,
    servingSize: "30g scoop",
    image: "https://i.imgur.com/DqEYOwv.jpg",
  },

];


async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    await Food.deleteMany({});
    await Food.insertMany(foods);
    console.log("✅ Data seeded");
    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

seed();
